PIG_WEIGHTS_CONFIG = {
    "sheet_names": {
        "pig_overview": "PIG_OVERVIEW",
        "pig_master": "PIG_MASTER",
        "weight_log": "WEIGHT_LOG",
        "medical_log": "MEDICAL_LOG",
        "product_register": "PRODUCT_REGISTER",
        "location_history": "LOCATION_HISTORY",
        "pen_register": "PEN_REGISTER",
        "sales_availability": "SALES_AVAILABILITY",
        "litter_register": "LITTERS",
    },
    "columns": {
        "pig_id": "Pig_ID",
        "tag_number": "Tag_Number",
        "status": "Status",
        "on_farm": "On_Farm",
        "current_weight": "Current_Weight_Kg",
        "last_weight_date": "Last_Weight_Date",

        "weight_log_id": "Weight_Log_ID",
        "weight_date": "Weight_Date",
        "weight_kg": "Weight_Kg",
        "condition_notes": "Condition_Notes",
        "weighed_by": "Weighed_By",

        "medical_log_id": "Medical_Log_ID",
        "treatment_date": "Treatment_Date",
        "treatment_type": "Treatment_Type",
        "product_id": "Product_ID",
        "product_name": "Product_Name",
        "dose": "Dose",
        "dose_unit": "Dose_Unit",
        "route": "Route",
        "reason_for_treatment": "Reason_For_Treatment",
        "batch_lot_number": "Batch_Lot_Number",
        "withdrawal_days": "Withdrawal_Days",
        "withdrawal_end_date": "Withdrawal_End_Date",
        "given_by": "Given_By",
        "follow_up_required": "Follow_Up_Required",
        "follow_up_date": "Follow_Up_Date",
        "medical_notes": "Medical_Notes",
        "created_at": "Created_At",

        "product_category": "Product_Category",
        "default_dose": "Default_Dose",
        "default_withdrawal_days": "Default_Withdrawal_Days",
        "supplier": "Supplier",
        "batch_tracking_required": "Batch_Tracking_Required",
        "is_active": "Is_Active",
        "product_notes": "Product_Notes",

        "move_log_id": "Move_Log_ID",
        "move_date": "Move_Date",
        "from_pen_id": "From_Pen_ID",
        "to_pen_id": "To_Pen_ID",
        "reason_for_move": "Reason_For_Move",
        "moved_by": "Moved_By",
        "group_batch_id": "Group_Batch_ID",
        "move_notes": "Move_Notes",

        "pen_id": "Pen_ID",
        "pen_name": "Pen_Name",
        "pen_type": "Pen_Type",
        "capacity": "Capacity",
        "pen_notes": "Pen_Notes",

        "age_days": "Age_Days",
        "sex": "Sex",
        "average_daily_gain": "Average_Daily_Gain_Kg",
        "calculated_stage": "Calculated_Stage",
        "weight_band": "Weight_Band",
        "current_pen_id": "Current_Pen_ID",
        "withdrawal_clear": "Withdrawal_Clear",
        "reserved_status": "Reserved_Status",
        "reserved_for_order_id": "Reserved_For_Order_ID",
        "available_for_sale": "Available_For_Sale",
        "sale_category": "Sale_Category",
        "suggested_price_category": "Suggested_Price_Category",
        "sales_notes": "Sales_Notes",
    }
}