const assert = require("assert");
const fs = require("fs");

const html = fs.readFileSync("templates/breeding-attention.html", "utf8");
const js = fs.readFileSync("static/js/breedingAttention.js", "utf8");

assert(html.includes('id="attention_filter"'));
assert(html.includes("Huidige teelstatus en volgende stap"));
assert(html.includes("Volgende menslike stap"));
assert(html.includes("farmDashboardV2.css"));
assert(html.includes("breedingAttentionV2.css"));
assert(html.includes("_farm_nav.html"));
assert(js.includes('fetch(apiUrl("/breeding-attention"))'));
assert(js.includes('Jongste waarneming') || html.includes('Jongste waarneming'));
assert(js.includes('observationSummaryCell'));
assert(js.includes("tellings is nie noodwendig nul nie."));
assert(html.includes('id="observation_panel"'));
assert(html.includes("Waarneming, eienaarinterpretasie en HERDMASTER-aanbeveling bly apart."));
assert(html.includes("Wat het jy gesien?"));
assert(js.includes("/observations/preview"));
assert(js.includes("/observations`"));
assert(js.includes("acceptedPreviewPayload"));
assert(js.includes("recordButton.disabled = true"));
assert(js.includes("crypto.randomUUID()"));
assert(js.includes("Indien aangeteken:"));
assert(js.includes("refreshObservationHistory"));
assert(js.includes("AANGETEKEN — hierdie waarneming is veilig gestoor"));
assert(js.includes("Moenie dit weer invoer nie"));
assert(html.includes('id="observation_history"'));
assert(!html.includes("customer"));
console.log("breeding attention browser contract passed");
