from pathlib import Path
import unittest


class FrontendRouteContractTests(unittest.TestCase):
    def test_oom_sakkie_audit_rail_ci_and_browser_checklist_are_documented(self):
        workflow = Path(".github/workflows/oom-sakkie-audit-rails.yml").read_text(encoding="utf-8")
        checklist = Path("docs/06-operations/OOM_SAKKIE_BROWSER_BEHAVIOR_CHECKLIST.md").read_text(encoding="utf-8")
        playwright_workflow = Path(".github/workflows/oom-sakkie-browser-behavior.yml").read_text(encoding="utf-8")
        playwright_spec = Path("tests/oom_sakkie_playwright_behavior.spec.js").read_text(encoding="utf-8")
        playwright_config = Path("playwright.config.js").read_text(encoding="utf-8")
        package_json = Path("package.json").read_text(encoding="utf-8")

        self.assertIn("postgres:16", workflow)
        self.assertIn('FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"', workflow)
        self.assertIn("DATABASE_URL: postgresql://postgres:postgres@localhost:5432/amadeus_test", workflow)
        self.assertIn("202606060001_create_oom_sakkie_traces.sql", workflow)
        self.assertIn("202606060004_lock_oom_sakkie_trace_append_only.sql", workflow)
        self.assertIn("202606070004_create_oom_sakkie_deploy_decisions.sql", workflow)
        self.assertIn("202606080002_create_oom_sakkie_agent_dry_run_results.sql", workflow)
        self.assertIn("202606090001_create_oom_sakkie_dispatch_decisions.sql", workflow)
        self.assertIn("202606090002_create_oom_sakkie_dispatch_execution_approvals.sql", workflow)
        self.assertIn("202606090003_allow_single_shot_sentinel_dry_run_results.sql", workflow)
        self.assertIn("202606100001_create_oom_sakkie_learning_influence_proposals.sql", workflow)
        self.assertIn("python -m unittest tests.test_oom_sakkie_service tests.test_oom_sakkie_routes tests.test_frontend_route_contracts", workflow)
        self.assertIn("node --check static/js/oomSakkie.js", workflow)
        self.assertIn("node tests/oom_sakkie_browser_behavior_smoke.js", workflow)

        self.assertIn("No specialist dispatch.", checklist)
        self.assertIn("No Background Polling", checklist)
        self.assertIn("Accepted agent learning", checklist)
        self.assertIn("Voice loop 5 of 5", checklist)
        self.assertIn("Every dry-run/result/event action is owner-clicked.", checklist)

        self.assertIn("Playwright real-browser behavior gate", playwright_workflow)
        self.assertIn('python-version: "3.12"', playwright_workflow)
        self.assertIn('FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"', playwright_workflow)
        self.assertIn('node-version: "24"', playwright_workflow)
        self.assertIn('FLASK_DEBUG: "0"', playwright_workflow)
        self.assertIn("python -m flask --app app run --host 127.0.0.1 --port 5000", playwright_workflow)
        self.assertIn('OOM_SAKKIE_PLAYWRIGHT_SERVER_URL: "http://127.0.0.1:5000/oom-sakkie"', playwright_workflow)
        self.assertNotIn("python app.py", playwright_workflow)
        self.assertIn("npm run test:oom-sakkie:browser", playwright_workflow)
        self.assertIn("npx playwright install --with-deps chromium", playwright_workflow)
        self.assertIn('"test:oom-sakkie:browser"', package_json)
        self.assertIn("@playwright/test", package_json)
        self.assertIn('testDir: "tests"', playwright_config)
        self.assertIn('testMatch: ["oom_sakkie_playwright_behavior.spec.js"]', playwright_config)
        self.assertIn("const serverURL = process.env.OOM_SAKKIE_PLAYWRIGHT_SERVER_URL", playwright_config)
        self.assertIn("url: serverURL", playwright_config)
        self.assertIn("window.__oomSakkieIntervals", playwright_spec)
        self.assertIn("kiosk startup performs no hidden POSTs or interval polling", playwright_spec)
        self.assertIn("dry-run/result/message POSTs require explicit owner clicks", playwright_spec)
        self.assertIn('page.locator(".oom-command-deck")', playwright_spec)
        self.assertIn('page.locator(".oom-quick-drawer")', playwright_spec)
        self.assertIn('.oom-command-deck [data-quick-ask]', playwright_spec)
        self.assertIn("stubOomSakkieApi", playwright_spec)
        self.assertIn('page.locator(".oom-system-workbench").evaluate', playwright_spec)
        self.assertIn('toBeVisible()', playwright_spec)

    def test_oom_sakkie_agent_dry_run_browser_behavior_contract(self):
        js = Path("static/js/oomSakkie.js").read_text(encoding="utf-8")

        self.assertNotIn("setInterval", js)
        self.assertIn('fetch("/api/oom-sakkie/agent-dry-runs?limit=8")', js)
        self.assertIn('fetch("/api/oom-sakkie/agent-dry-run-results?limit=8")', js)
        self.assertIn('fetch(`/api/oom-sakkie/agent-dry-run-results/${encodeURIComponent(dryRunResultId)}/review-packet`)', js)
        self.assertIn('fetch("/api/oom-sakkie/agent-dry-runs/handoff"', js)
        self.assertIn("recordAgentDryRunResultButton.addEventListener", js)
        self.assertIn("requestSentinelDryRunButton.addEventListener", js)
        self.assertIn("requestPrismDryRunButton.addEventListener", js)
        self.assertIn("requestSelectedAgentDryRunButton.addEventListener", js)
        self.assertIn("agentDryRunSpecialistSelect.value", js)
        self.assertIn("Approved dry-run candidates", js)
        self.assertIn('dry-run request ${item.dry_run_request_allowed ? "allowed" : "locked"}', js)
        self.assertIn('runtime ${item.allowed_now ? "on" : "locked"}', js)
        self.assertIn("acceptButton.addEventListener", js)
        self.assertIn("rejectButton.addEventListener", js)
        self.assertIn("noteButton.addEventListener", js)
        self.assertIn('recordAgentResultEvent(', js)
        self.assertIn('"accepted_for_learning"', js)
        self.assertIn('"rejected"', js)
        self.assertIn('"review_note"', js)
        self.assertIn("No agent dry-run requests need handoff right now.", js)
        self.assertIn("No closed agent dry-run requests yet.", js)
        self.assertIn("No agent results need owner review right now.", js)
        self.assertIn("No reviewed agent results yet.", js)

        render_reviews = js[js.index("function renderAgentResultReviews"):js.index("function renderAgentLearningLedger")]
        render_rows = js[js.index("function renderAgentResultRow"):js.index("function openAgentResultPacket")]
        render_requests = js[js.index("function renderAgentDryRunRequests"):js.index("function renderAgentDryRunRequestRow")]
        render_handoff = js[js.index("function renderAgentDryRunHandoff"):js.index("async function buildAgentDryRunHandoff")]

        self.assertNotIn("fetch(", render_reviews)
        self.assertNotIn("recordAgentResultEvent", render_reviews)
        self.assertNotIn("fetch(", render_requests)
        self.assertNotIn("fetch(", render_handoff)
        self.assertNotIn("/events", render_handoff)
        self.assertIn("recordAgentResultEvent", render_rows)
        self.assertIn("openAgentResultPacket", render_rows)

    def test_oom_sakkie_browser_behavior_smoke_executes_real_kiosk_script(self):
        smoke = Path("tests/oom_sakkie_browser_behavior_smoke.js").read_text(encoding="utf-8")

        self.assertIn('fs.readFileSync(path.join(__dirname, "..", "static", "js", "oomSakkie.js")', smoke)
        self.assertIn("vm.runInNewContext(source, sandbox", smoke)
        self.assertIn("kiosk startup must not create background polling intervals", smoke)
        self.assertIn("kiosk startup must not perform hidden POST requests", smoke)
        self.assertIn("Sentinel dry-run request must POST only after owner click", smoke)
        self.assertIn("Agent dry-run result recording must POST only after owner click", smoke)
        self.assertIn("quick ask should POST a single owner-triggered message", smoke)

    def test_oom_sakkie_kiosk_page_and_api_are_registered(self):
        app_source = Path("app.py").read_text(encoding="utf-8")
        template = Path("templates/oom-sakkie.html").read_text(encoding="utf-8")
        js = Path("static/js/oomSakkie.js").read_text(encoding="utf-8")
        css = Path("static/css/main.css").read_text(encoding="utf-8")
        route_source = Path("modules/oom_sakkie/routes.py").read_text(encoding="utf-8")

        self.assertIn('@app.route("/oom-sakkie")', app_source)
        self.assertIn('render_template("oom-sakkie.html")', app_source)
        self.assertIn('app.register_blueprint(oom_sakkie_bp, url_prefix="/api")', app_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/message", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/tools", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/policy", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/specialists", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agents", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agents/contracts", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agents/preflight", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agents/authority-matrix", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agents/unlock-readiness", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agents/dispatch-rail-blueprint", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agents/runtime-review-packet", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agents/recommend", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agent-dry-runs", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agent-dry-runs", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agent-dry-runs/<dry_run_request_id>/events", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agent-dry-runs/handoff", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agent-dry-runs/<dry_run_request_id>/results", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agent-dry-run-results", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agent-dry-run-results/<dry_run_result_id>/events", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/agent-dry-run-results/<dry_run_result_id>/review-packet", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/review-packet", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/review-advisor", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/learning-advisor", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/learning-advisor/analyze", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/learning-advisor/build-packet", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/learning-advisor/implementation-queue", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/learning-advisor/approve-build", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/build-requests", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/build-requests/<build_request_id>/events", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/build-requests/forge-handoff", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/build-requests/<build_request_id>/patch-proposals", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/patch-proposals", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/patch-proposals/<patch_proposal_id>/events", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/patch-proposals/<patch_proposal_id>/deploy-decisions", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/deploy-decisions", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/dispatch-requests", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/dispatch-requests", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/dispatch-requests/<dispatch_request_id>/decisions", methods=["POST"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/traces", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/traces/review-summary", methods=["GET"])', route_source)
        self.assertIn('@oom_sakkie_bp.route("/oom-sakkie/traces/<trace_id>/feedback", methods=["POST"])', route_source)
        self.assertIn('id="oom_form"', template)
        self.assertIn('class="oom-presence-panel"', template)
        self.assertIn('id="oom_presence_orb"', template)
        self.assertIn('id="oom_presence_line"', template)
        self.assertIn('class="oom-presence-actions"', template)
        self.assertIn("Agent Presence", template)
        self.assertIn('class="oom-agent-stage"', template)
        self.assertIn('id="oom_agent_controller_state"', template)
        self.assertIn('id="oom_active_agent_workspace"', template)
        self.assertIn('id="oom_active_agent_name"', template)
        self.assertIn('id="oom_active_agent_title"', template)
        self.assertIn('id="oom_active_agent_detail"', template)
        self.assertIn('id="oom_active_agent_guard"', template)
        self.assertIn('id="oom_agent_handoff_lane"', template)
        self.assertIn('id="oom_agent_crew_sequence"', template)
        self.assertIn('class="oom-controller-board"', template)
        self.assertIn('id="oom_controller_mission"', template)
        self.assertIn('id="oom_controller_detail"', template)
        self.assertIn('id="oom_specialist_mission"', template)
        self.assertIn('id="oom_specialist_detail"', template)
        self.assertIn('id="oom_owner_gate_mission"', template)
        self.assertIn('id="oom_owner_gate_detail"', template)
        self.assertIn("Owner Gate", template)
        self.assertIn("Agent handoff lane", template)
        self.assertIn("Planned specialist sequence", template)
        self.assertIn("Handoff lane opens after a read-only check.", template)
        self.assertIn("Agent activity stage", template)
        self.assertIn("Controller standing by", template)
        self.assertIn("No specialist workspace open", template)
        self.assertIn('class="oom-approval-console"', template)
        self.assertIn("Needs Your Approval", template)
        self.assertIn('id="oom_approval_console"', template)
        self.assertIn('id="oom_refresh_approval_console"', template)
        self.assertIn("Current decisions only. Full traceability stays in the System Workbench.", template)
        self.assertIn("function renderApprovalConsole", js)
        self.assertIn("function currentApprovalItems", js)
        self.assertIn("function openWorkbenchSection", js)
        self.assertIn("No owner approvals waiting right now.", js)
        self.assertIn("Start with the first card. Each action opens the exact review area below.", js)
        self.assertIn("refreshApprovalConsole.addEventListener", js)
        self.assertIn(".oom-system-workbench", js)
        self.assertIn(".oom-approval-console", css)
        self.assertIn(".oom-approval-item", css)
        self.assertIn(".oom-approval-action", css)
        self.assertIn('id="oom_answer"', template)
        self.assertIn('class="oom-command-deck"', template)
        self.assertIn("Primary command deck", template)
        self.assertIn("Start Day", template)
        self.assertIn("Daily command brief", template)
        self.assertIn("Needs approval", template)
        self.assertIn("Control Tower", template)
        self.assertIn("Agent command center", template)
        self.assertIn("Gate status", template)
        self.assertIn('id="oom_safety_notes"', template)
        self.assertIn('id="oom_voice_button"', template)
        self.assertIn('id="oom_voice_ask_button"', template)
        self.assertIn('id="oom_voice_status"', template)
        self.assertIn('id="oom_voice_loop_counter"', template)
        self.assertIn("Voice loop 0 of 5", template)
        self.assertIn('id="oom_cancel_voice_send"', template)
        self.assertIn("Cancel Send", template)
        self.assertIn('id="oom_stop_conversation"', template)
        self.assertIn("Stop Conversation", template)
        self.assertIn('Voice loop stop words: "stop conversation", "cancel", or "never mind".', template)
        self.assertIn('id="oom_speak_answer"', template)
        self.assertIn('id="oom_stop_speech"', template)
        self.assertIn('id="oom_auto_speak"', template)
        self.assertIn("Speak replies", template)
        self.assertIn('id="oom_continue_conversation"', template)
        self.assertIn("Continue conversation", template)
        self.assertIn('class="oom-quick-drawer"', template)
        self.assertIn("More read-only checks", template)
        self.assertIn("Farm, business, and agent review shortcuts", template)
        self.assertIn('class="oom-quick-group" aria-label="Farm checks"', template)
        self.assertIn('class="oom-quick-group" aria-label="Business checks"', template)
        self.assertIn('class="oom-quick-group" aria-label="Agent and review checks"', template)
        self.assertIn("Agent Review", template)
        self.assertIn('data-quick-ask="Give me the daily command brief."', template)
        self.assertIn('data-quick-ask="What needs attention today?"', template)
        self.assertIn('data-quick-ask="What is the power doing now?"', template)
        self.assertIn('data-quick-ask="What happened with the weather today?"', template)
        self.assertIn('data-quick-ask="What pigs are ready for meat?"', template)
        self.assertIn('data-quick-ask="Show me the sales dashboard overview."', template)
        self.assertIn('data-quick-ask="What should we sell next?"', template)
        self.assertIn('data-quick-ask="Prepare an internal offer brief."', template)
        self.assertIn('data-quick-ask="What is the irrigation status?"', template)
        self.assertIn('data-quick-ask="What needs my approval?"', template)
        self.assertIn('data-quick-ask="Show me the agent command center."', template)
        self.assertIn("Command Center", template)
        self.assertIn('data-quick-ask="Show me the safety gates."', template)
        self.assertIn("Safety Gates", template)
        self.assertIn('data-quick-ask="Prepare Claude review."', template)
        self.assertIn("Review Packet", template)
        self.assertIn('data-quick-ask="Which agent should handle this?"', template)
        self.assertIn('data-quick-ask="Give me the agent team brief for growing the farm business."', template)
        self.assertIn('data-quick-ask="What is the agent activation plan?"', template)
        self.assertIn('data-quick-ask="Run the Sentinel dry-run review."', template)
        self.assertIn('data-quick-ask="What is the Sentinel dry-run result queue status?"', template)
        self.assertIn('data-quick-ask="What did Sentinel learn from accepted results?"', template)
        self.assertIn('id="oom_trace_id"', template)
        self.assertIn('id="oom_recent_traces"', template)
        self.assertIn('id="oom_route_source"', template)
        self.assertIn('id="oom_answer_source"', template)
        self.assertIn('id="oom_pipeline_state"', template)
        self.assertIn('id="oom_intent_confidence"', template)
        self.assertIn('id="oom_intent_reason"', template)
        self.assertIn('id="oom_refresh_traces"', template)
        self.assertIn('id="oom_review_summary"', template)
        self.assertIn('id="oom_voice_checks"', template)
        self.assertIn('id="oom_voice_events"', template)
        self.assertIn('id="oom_clear_voice_events"', template)
        self.assertIn('id="oom_tool_catalog"', template)
        self.assertIn('id="oom_refresh_tools"', template)
        self.assertIn("Available Checks", template)
        self.assertIn("Runtime tool registry. This kiosk is read-only.", template)
        self.assertIn('id="oom_policy_status"', template)
        self.assertIn('id="oom_refresh_policy"', template)
        self.assertIn("Safety Status", template)
        self.assertIn("Runtime guardrails for this local kiosk.", template)
        self.assertIn('id="oom_agent_crew"', template)
        self.assertIn('id="oom_refresh_agents"', template)
        self.assertIn("Agent Crew Foundation", template)
        self.assertIn("Live dispatch is still off.", template)
        self.assertIn('id="oom_agent_roadmap"', template)
        self.assertIn('id="oom_refresh_agent_roadmap"', template)
        self.assertIn('id="oom_request_sentinel_dry_run"', template)
        self.assertIn('id="oom_request_prism_dry_run"', template)
        self.assertIn('id="oom_agent_dry_run_specialist_select"', template)
        self.assertIn('id="oom_request_selected_agent_dry_run"', template)
        self.assertIn("Agent Roadmap", template)
        self.assertIn("Request Sentinel Dry-Run", template)
        self.assertIn("Request Prism Dry-Run", template)
        self.assertIn("Request Selected Dry-Run", template)
        self.assertIn("Ledger - business", template)
        self.assertIn("Atlas - analytics", template)
        self.assertIn("Rootline - weather/irrigation", template)
        self.assertIn("Herdmaster - pigs", template)
        self.assertIn("Butcher - pork pipeline", template)
        self.assertIn("Quartermaster - operations", template)
        self.assertIn("Activation stages and accepted learning. Planning only.", template)
        self.assertIn('id="oom_agent_dry_run_requests"', template)
        self.assertIn('id="oom_refresh_agent_dry_run_requests"', template)
        self.assertIn('id="oom_agent_dry_run_handoff"', template)
        self.assertIn('id="oom_agent_dry_run_result_request_id"', template)
        self.assertIn('id="oom_agent_dry_run_result_text"', template)
        self.assertIn('id="oom_agent_dry_run_result_findings"', template)
        self.assertIn('id="oom_record_agent_dry_run_result"', template)
        self.assertIn("Agent Dry-Run Requests", template)
        self.assertIn("Record Agent Result", template)
        self.assertIn("Agents do not run here.", template)
        self.assertIn("This does not run an agent or apply learning.", template)
        self.assertIn("Paste agent dry-run result text for owner review.", template)
        self.assertIn('id="oom_agent_result_reviews"', template)
        self.assertIn('id="oom_refresh_agent_result_reviews"', template)
        self.assertIn("Agent Result Review", template)
        self.assertIn("No specialist runs here.", template)
        self.assertIn('id="oom_agent_learning_ledger"', template)
        self.assertIn('id="oom_refresh_agent_learning_ledger"', template)
        self.assertIn("Agent Learning Ledger", template)
        self.assertIn("Accepted dry-run evidence only.", template)
        self.assertIn("Accepted agent learning", js)
        self.assertIn("Accepted agent evidence", js)
        self.assertIn("accepted by specialist", js)
        self.assertIn("acceptedParts.join", js)
        self.assertIn('id="oom_review_advisor"', template)
        self.assertIn('id="oom_refresh_advisor"', template)
        self.assertIn("Advisory queue only. It never marks feedback automatically.", template)
        self.assertIn('id="oom_learning_advisor"', template)
        self.assertIn('id="oom_learning_packet"', template)
        self.assertIn('id="oom_implementation_queue"', template)
        self.assertIn('id="oom_refresh_implementation_queue"', template)
        self.assertIn('id="oom_build_requests"', template)
        self.assertIn('id="oom_forge_handoff"', template)
        self.assertIn('id="oom_refresh_build_requests"', template)
        self.assertIn('id="oom_patch_build_request_id"', template)
        self.assertIn('id="oom_patch_proposal_text"', template)
        self.assertIn('id="oom_record_patch_proposal"', template)
        self.assertIn('id="oom_patch_proposals"', template)
        self.assertIn('id="oom_refresh_patch_proposals"', template)
        self.assertIn('id="oom_deploy_patch_proposal_id"', template)
        self.assertIn('id="oom_deploy_verification_summary"', template)
        self.assertIn('id="oom_approve_manual_deploy"', template)
        self.assertIn('id="oom_defer_deploy"', template)
        self.assertIn('id="oom_deploy_decisions"', template)
        self.assertIn('id="oom_refresh_deploy_decisions"', template)
        self.assertIn('id="oom_refresh_learning"', template)
        self.assertIn('id="oom_run_learning_analysis"', template)
        self.assertIn("Learning Queue", template)
        self.assertIn("Human-approved improvement proposals from reviewed traces.", template)
        self.assertIn("No build brief generated yet.", template)
        self.assertIn("Implementation Queue", template)
        self.assertIn("Auto-prepared briefs from strong learning signals. Approval is still manual.", template)
        self.assertIn("Approved Build Requests", template)
        self.assertIn("Persistent queue for future Builder/Forge work. No builder runs here.", template)
        self.assertIn("No Forge handoff generated yet.", template)
        self.assertIn('class="oom-system-workbench"', template)
        self.assertIn('id="oom_workbench_next_action"', template)
        self.assertIn("System Workbench", template)
        self.assertIn("Review traces, learning, build, patch, and deploy gates", template)
        self.assertIn("Patch Proposal Gate", template)
        self.assertIn("This does not apply a patch.", template)
        self.assertIn("Deploy Approval Gate", template)
        self.assertIn("It does not deploy.", template)
        self.assertIn("Voice Session", template)
        self.assertIn("Local browser events only. Nothing here is sent to Supabase.", template)
        self.assertIn("Voice Readiness", template)
        self.assertIn("No microphone is opened yet.", template)
        self.assertIn('data-review-filter="all"', template)
        self.assertIn('data-review-filter="unreviewed"', template)
        self.assertIn('data-review-filter="issues"', template)
        self.assertIn('data-review-filter="reviewed"', template)
        self.assertIn('/api/oom-sakkie/review-packet?channel=kiosk&limit=12&days=14', template)
        self.assertIn("Review Packet", template)
        self.assertIn('/api/oom-sakkie/review-advisor?channel=kiosk&limit=12&days=14', template)
        self.assertIn("Review Advisor", template)
        self.assertIn('/api/oom-sakkie/specialists', template)
        self.assertIn("Specialists", template)
        self.assertIn('/api/oom-sakkie/agents', template)
        self.assertIn("Agents", template)
        self.assertIn('id="oom_trace_search"', template)
        self.assertIn('id="oom_clear_trace_search"', template)
        self.assertIn("oom-trace-panel", template)
        self.assertIn("/api/oom-sakkie/message", js)
        self.assertIn("/api/oom-sakkie/tools", js)
        self.assertIn("/api/oom-sakkie/policy", js)
        self.assertIn("/api/oom-sakkie/review-advisor?channel=kiosk&days=14&limit=12", js)
        self.assertIn("/api/oom-sakkie/traces?channel=kiosk&limit=8&review=", js)
        self.assertIn("&q=", js)
        self.assertIn("traceSearch", js)
        self.assertIn("clearTraceSearch", js)
        self.assertIn("quickAskButtons", js)
        self.assertIn("button.dataset.quickAsk", js)
        self.assertIn("renderAgentCrew", js)
        self.assertIn("function renderAgentResultReviews(data)", js)
        self.assertIn("function renderAgentResultRow(item)", js)
        self.assertIn("function renderAgentLearningLedger(data)", js)
        self.assertIn("function renderAgentLearningLedgerRow(item)", js)
        self.assertIn("accepted evidence only", js)
        self.assertIn("function openAgentResultPacket", js)
        self.assertIn("function recordAgentResultEvent", js)
        self.assertIn("Evidence kind:", js)
        self.assertIn("May influence:", js)
        self.assertIn("Must not influence:", js)
        self.assertIn("Owner question:", js)
        self.assertIn('latestEvent.event_type === "review_note"', js)
        self.assertIn("/api/oom-sakkie/agent-dry-run-results?limit=8", js)
        self.assertIn("/review-packet", js)
        self.assertIn("accepted_for_learning", js)
        self.assertIn('fetch("/api/oom-sakkie/agents")', js)
        self.assertIn("loadAgentCrew", js)
        self.assertIn('fetch("/api/oom-sakkie/agents/activation-plan?limit=20")', js)
        self.assertIn("function renderAgentRoadmap(data)", js)
        self.assertIn("function loadAgentRoadmap()", js)
        self.assertIn("function requestSentinelDryRun(button)", js)
        self.assertIn("function requestPrismDryRun(button)", js)
        self.assertIn("function renderAgentRoadmapRequestResult(data)", js)
        self.assertIn('/api/oom-sakkie/agent-dry-runs"', js)
        self.assertIn('specialist_slug: "sentinel"', js)
        self.assertIn('specialist_slug: "prism"', js)
        self.assertIn("${specialistName} did not run", js)
        self.assertIn("Do not run Prism", js)
        self.assertIn("function renderAgentDryRunRequests(data)", js)
        self.assertIn("function renderAgentDryRunRequestRow(item)", js)
        self.assertIn("function renderAgentDryRunHandoff(data)", js)
        self.assertIn("function buildAgentDryRunHandoff(dryRunRequestId, button)", js)
        self.assertIn("function recordAgentDryRunResult(button)", js)
        self.assertIn('fetch("/api/oom-sakkie/agent-dry-runs?limit=8")', js)
        self.assertIn('fetch("/api/oom-sakkie/agent-dry-runs/handoff"', js)
        self.assertIn("/results`,", js)
        self.assertIn("Copy Sentinel Handoff", js)
        self.assertIn("Use For Result", js)
        self.assertIn("accepted evidence ${data.accepted_learning_count || 0}", js)
        self.assertIn("planning only | owner approval required | runtime locked", js)
        self.assertIn('SESSION_STORAGE_KEY = "oom_sakkie_session_id"', js)
        self.assertIn("function getSessionId()", js)
        self.assertIn("window.localStorage.getItem(SESSION_STORAGE_KEY)", js)
        self.assertIn("window.localStorage.setItem(SESSION_STORAGE_KEY, generated)", js)
        self.assertIn("session_id: getSessionId()", js)
        self.assertIn("function renderPipeline(data)", js)
        self.assertIn("function resetPipelineForCheck()", js)
        self.assertIn("function setPresenceState(state, label)", js)
        self.assertIn("presenceOrb.dataset.state", js)
        self.assertIn("function renderAgentActivity(data)", js)
        self.assertIn("function renderAgentHandoffLane(items)", js)
        self.assertIn("function renderAgentCrewSequence(items)", js)
        self.assertIn("function renderControllerBoard(activity)", js)
        self.assertIn("data.agent_activity", js)
        self.assertIn("activity.handoff_lane", js)
        self.assertIn("activity.crew_sequence", js)
        self.assertIn("renderControllerBoard(activity)", js)
        self.assertIn("renderControllerBoard(null)", js)
        self.assertIn("Oom Sakkie will route the next read-only check.", js)
        self.assertIn("No action was taken; owner gates remain manual.", js)
        self.assertIn("agentCrewSequence.hidden = true", js)
        self.assertIn("oom-agent-sequence-card", js)
        self.assertIn("agentHandoffLane.innerHTML = \"\"", js)
        self.assertIn("document.createElement(\"article\")", js)
        self.assertIn("oom-agent-handoff-card", js)
        self.assertIn("activeAgentWorkspace.dataset.agent", js)
        self.assertIn("presenceOrb.dataset.agent", js)
        self.assertIn("Coordinating ${agent.name || slug}", js)
        self.assertIn("dispatch ${safety.dispatch_enabled ? \"on\" : \"off\"}", js)
        self.assertIn("Standing by for a read-only farm check.", js)
        self.assertIn("Speaking. Mic is paused.", js)
        self.assertIn("Blocked safely. No action was taken.", js)
        self.assertIn("pipeline.route_source", js)
        self.assertIn("pipeline.answer_source", js)
        self.assertIn("intent.reason", js)
        self.assertIn("statusBadge.dataset.state", js)
        self.assertIn("traceSearchTimer", js)
        self.assertIn("window.setTimeout(loadRecentTraces, 220)", js)
        self.assertIn("renderVoiceReadiness", js)
        self.assertIn("renderSafetyNotes", js)
        self.assertIn("window.isSecureContext", js)
        self.assertIn("window.SpeechRecognition || window.webkitSpeechRecognition", js)
        self.assertIn("ensureRecognition", js)
        self.assertIn("toggleVoiceDraft", js)
        self.assertIn("toggleVoiceAsk", js)
        self.assertIn("scheduleVoiceAutoSubmit", js)
        self.assertIn("clearVoiceAutoSubmit", js)
        self.assertIn("voiceAutoSubmitMode", js)
        self.assertIn("voiceAutoSubmitTimer", js)
        self.assertIn("window.setTimeout(() =>", js)
        self.assertIn("}, 2000)", js)
        self.assertIn("Sending in 2 seconds unless you cancel or edit.", js)
        self.assertIn("Voice send cancelled because the text changed.", js)
        self.assertIn('recognition.lang = "en-ZA"', js)
        self.assertIn("recognition.interimResults = true", js)
        self.assertIn("recognition.continuous = false", js)
        self.assertIn("setVoiceStatus", js)
        self.assertIn("Heard draft. Check the text, then press Ask.", js)
        self.assertIn("voiceButton.disabled = !SpeechRecognition", js)
        self.assertIn("voiceAskButton.disabled = !SpeechRecognition", js)
        self.assertIn("speechSynthesisApi", js)
        self.assertIn("SpeechSynthesisUtterance", js)
        self.assertIn("speakCurrentAnswer", js)
        self.assertIn("stopSpeech", js)
        self.assertIn("autoSpeak", js)
        self.assertIn("continueConversation", js)
        self.assertIn("shouldContinueConversation", js)
        self.assertIn("MAX_CONTINUE_TURNS = 5", js)
        self.assertIn("voiceLoopTurnCount", js)
        self.assertIn("voiceLoopCounter", js)
        self.assertIn("renderVoiceLoopCounter", js)
        self.assertIn("Voice loop ${Math.min(voiceLoopTurnCount, MAX_CONTINUE_TURNS)} of ${MAX_CONTINUE_TURNS}", js)
        self.assertIn("MAX_VOICE_EVENTS = 12", js)
        self.assertIn("voiceEventLog", js)
        self.assertIn("logVoiceEvent", js)
        self.assertIn("renderVoiceEvents", js)
        self.assertIn("loadToolCatalog", js)
        self.assertIn("renderToolCatalog", js)
        self.assertIn("loadPolicyStatus", js)
        self.assertIn("renderPolicyStatus", js)
        self.assertIn("llmRouter", js)
        self.assertIn("llmAnswer", js)
        self.assertIn("LLM fallback", js)
        self.assertIn("LLM configured", js)
        self.assertIn("LLM sends text", js)
        self.assertIn("outbound_endpoint_when_enabled", js)
        self.assertIn("sends_user_text_when_enabled", js)
        self.assertIn("LLM answer", js)
        self.assertIn("Answer sends summary", js)
        self.assertIn("sends_tool_summary_when_enabled", js)
        self.assertIn("Answer sends context", js)
        self.assertIn("sends_capped_tool_context_when_enabled", js)
        self.assertIn("loadReviewAdvisor", js)
        self.assertIn("renderReviewAdvisor", js)
        self.assertIn("loadLearningAdvisor", js)
        self.assertIn("renderLearningAdvisor", js)
        self.assertIn("analyzeLearningAdvisor", js)
        self.assertIn("renderLearningAnalysis", js)
        self.assertIn("buildLearningPacket", js)
        self.assertIn("approveBuildRequest", js)
        self.assertIn("renderLearningPacket", js)
        self.assertIn("renderBuildApproval", js)
        self.assertIn("renderLearningProposalList", js)
        self.assertIn("loadImplementationQueue", js)
        self.assertIn("renderImplementationQueue", js)
        self.assertIn("loadBuildRequests", js)
        self.assertIn("renderBuildRequests", js)
        self.assertIn("recordBuildRequestEvent", js)
        self.assertIn("buildForgeHandoff", js)
        self.assertIn("renderForgeHandoff", js)
        self.assertIn("/api/oom-sakkie/learning-advisor?channel=kiosk&days=14&limit=12", js)
        self.assertIn("/api/oom-sakkie/learning-advisor/analyze", js)
        self.assertIn("/api/oom-sakkie/learning-advisor/build-packet", js)
        self.assertIn("/api/oom-sakkie/learning-advisor/approve-build", js)
        self.assertIn("/api/oom-sakkie/learning-advisor/implementation-queue?channel=kiosk&days=14&limit=12", js)
        self.assertIn("/api/oom-sakkie/build-requests?limit=8", js)
        self.assertIn('/api/oom-sakkie/build-requests/${encodeURIComponent(buildRequestId)}/events', js)
        self.assertIn("/api/oom-sakkie/build-requests/forge-handoff", js)
        self.assertIn("body: JSON.stringify({ build_request_id: buildRequestId })", js)
        self.assertIn("/api/oom-sakkie/patch-proposals?limit=8", js)
        self.assertIn('/api/oom-sakkie/build-requests/${encodeURIComponent(buildRequestId)}/patch-proposals', js)
        self.assertIn('/api/oom-sakkie/patch-proposals/${encodeURIComponent(patchProposalId)}/events', js)
        self.assertIn("renderPatchProposals", js)
        self.assertIn("recordPatchProposal", js)
        self.assertIn("recordPatchProposalEvent", js)
        self.assertIn("Record Patch Proposal", js)
        self.assertIn("Approve Patch", js)
        self.assertIn("approved_for_patch", js)
        self.assertIn("Rejected from kiosk review.", js)
        self.assertIn("This records review data only; it does not apply a patch.", js)
        self.assertIn("applies patches", js)
        self.assertIn("manual owner gate required", js)
        self.assertIn("/api/oom-sakkie/deploy-decisions?limit=8", js)
        self.assertIn('/api/oom-sakkie/patch-proposals/${encodeURIComponent(patchProposalId)}/deploy-decisions', js)
        self.assertIn("renderDeployDecisions", js)
        self.assertIn("recordDeployDecision", js)
        self.assertIn("Prepare Deploy Decision", js)
        self.assertIn("Approve Manual Deploy", template)
        self.assertIn("approved_for_manual_deploy", js)
        self.assertIn("Deploy deferred from kiosk review. No deploy was run here.", js)
        self.assertIn("runs deploy", js)
        self.assertIn("deploys now", js)
        self.assertIn('method: "POST"', js)
        self.assertIn("Running learning analysis", js)
        self.assertIn("Build Brief", js)
        self.assertIn("Building review brief", js)
        self.assertIn("Open Brief", js)
        self.assertIn("Approve for Build", js)
        self.assertIn("builder enabled", js)
        self.assertIn("writes now", js)
        self.assertIn("applies now", js)
        self.assertIn("persistent queue", js)
        self.assertIn("Build request store", js)
        self.assertIn("Latest event", js)
        self.assertIn("Ignore", js)
        self.assertIn("Forge Handoff", js)
        self.assertIn("runs builder", js)
        self.assertIn("deploys", js)
        self.assertIn("owner must explicitly run Builder/Forge", js)
        self.assertIn("Copy Forge Prompt", js)
        self.assertIn("Use This Build Request In Patch Gate", js)
        self.assertIn("copyTextToClipboard", js)
        self.assertIn("navigator.clipboard.writeText", js)
        self.assertIn("Needs Forge Handoff / Builder Plan", js)
        self.assertIn("Already Moved Or Closed", js)
        self.assertIn("Needs Patch Review", js)
        self.assertIn("Approved - Ready For Deploy Decision", js)
        self.assertIn("Patch proposal recorded; moved to Patch Proposal Gate.", js)
        self.assertIn("What this needs now", js)
        self.assertIn("Paste what you verified", js)
        self.assertIn("Run the verification commands from the proposal.", js)
        self.assertIn("renderWorkbenchNextAction", js)
        self.assertIn("Next action", js)
        self.assertIn("latestAgentDryRunRequestsData", js)
        self.assertIn("pendingAgentRequests", js)
        self.assertIn("Agent handoff", js)
        self.assertIn("Open agent handoff for", js)
        self.assertIn("build handoff", js)
        self.assertIn("patch review", js)
        self.assertIn("deploy decision", js)
        self.assertIn("appendQueueSection", js)
        self.assertIn("buildRequestStage", js)
        self.assertIn("patchProposalStage", js)
        self.assertIn("Auto-prepare threshold", js)
        self.assertIn("writes code", js)
        self.assertIn("applies changes", js)
        self.assertIn("writes code", js)
        self.assertIn("approval", js)
        self.assertIn("auto-marking", js)
        self.assertIn("last ${data.days || 14} days", js)
        self.assertIn("data.mode", js)
        self.assertIn("data.autonomous_marking_enabled", js)
        self.assertIn("data.writes_feedback", js)
        self.assertIn("telegram_cutover_enabled", js)
        self.assertIn("always_on_mic_enabled", js)
        self.assertIn("continue_conversation_max_turns", js)
        self.assertIn("voice_auto_send_ms", js)
        self.assertIn("review_endpoints_access", js)
        self.assertIn("message_endpoint_access", js)
        self.assertIn("Review access", js)
        self.assertIn("Message access", js)
        self.assertIn("tool.requires_confirmation", js)
        self.assertIn("risk_label", js)
        self.assertIn("Backend answered", js)
        self.assertIn("Auto-send scheduled", js)
        self.assertIn("Stop phrase heard", js)
        self.assertIn("stopConversation", js)
        self.assertIn("isVoiceStopCommand", js)
        self.assertIn('"stop conversation"', js)
        self.assertIn('"never mind"', js)
        self.assertIn('"cancel send"', js)
        self.assertIn("Voice stop command heard. Conversation stopped.", js)
        self.assertIn("updateConversationStopVisibility", js)
        self.assertIn("preserveVoiceLoopCountForAsk", js)
        self.assertIn("Conversation paused after 5 continued turns.", js)
        self.assertIn("startVoiceAskCapture(false)", js)
        self.assertIn("Speech finished. Listening for the next question.", js)
        self.assertIn("Continue conversation is on.", js)
        self.assertIn("autoSpeak.checked = true", js)
        self.assertIn("speechRunId", js)
        self.assertIn('speechUtterance.lang = "en-ZA"', js)
        self.assertIn("speechUtterance.rate = 0.95", js)
        self.assertIn("recognition.stop()", js)
        self.assertIn("speechSynthesisApi.cancel()", js)
        self.assertIn("Mic is not listening.", js)
        self.assertIn("Mic stayed off.", js)
        self.assertNotIn("getUserMedia(", js)
        self.assertNotIn("ask(transcript", js)
        self.assertNotIn("continueAfterCurrentSpeech", js)
        self.assertIn("/api/oom-sakkie/traces/review-summary?channel=kiosk&days=14", js)
        self.assertIn('/api/oom-sakkie/traces/${encodeURIComponent(traceIdValue)}/feedback', js)
        self.assertIn("loadRecentTraces", js)
        self.assertIn("loadReviewSummary", js)
        self.assertIn("refreshReviewData", js)
        self.assertIn("setActiveReviewFilter", js)
        self.assertIn("activeReviewFilter", js)
        self.assertIn("buildTraceDetails", js)
        self.assertIn("buildTraceWarnings", js)
        self.assertIn("buildTraceSafetyNotes", js)
        self.assertIn("buildTraceLinks", js)
        self.assertIn("Show saved answer", js)
        self.assertIn("item.answer", js)
        self.assertIn("item.tool_result_summary", js)
        self.assertIn("item.stale_warnings", js)
        self.assertIn("item.safety_notes", js)
        self.assertIn("saveTraceFeedback", js)
        self.assertIn("latest_feedback", js)
        self.assertIn("feedback_type", js)
        self.assertIn("wrong_tool", js)
        self.assertIn('channel: "kiosk"', js)
        self.assertIn(".oom-answer", css)
        self.assertIn(".oom-command-deck", css)
        self.assertIn(".oom-pipeline-strip", css)
        self.assertIn(".oom-presence-panel", css)
        self.assertIn(".oom-presence-orb", css)
        self.assertIn(".oom-presence-actions", css)
        self.assertIn(".oom-agent-stage", css)
        self.assertIn(".oom-agent-controller", css)
        self.assertIn(".oom-agent-workspace", css)
        self.assertIn(".oom-agent-handoff-lane", css)
        self.assertIn(".oom-agent-handoff-card", css)
        self.assertIn(".oom-controller-board", css)
        self.assertIn(".oom-agent-crew-sequence", css)
        self.assertIn(".oom-agent-sequence-card", css)
        self.assertIn(".oom-agent-sequence-heading", css)
        self.assertIn('.oom-agent-workspace[data-agent="green"]', css)
        self.assertIn('.oom-agent-workspace[data-agent="rose"]', css)
        self.assertIn('.oom-agent-workspace[data-agent="magenta"]', css)
        self.assertIn('.oom-agent-workspace[data-agent="teal"]', css)
        self.assertIn('.oom-agent-workspace[data-agent="amber"]', css)
        self.assertIn('.oom-agent-workspace[data-agent="blue"]', css)
        self.assertIn('.oom-agent-workspace[data-agent="cyan"]', css)
        self.assertIn('.oom-agent-workspace[data-agent="violet"]', css)
        self.assertIn('.oom-agent-workspace[data-agent="red"]', css)
        self.assertIn('.oom-agent-workspace[data-agent="olive"]', css)
        self.assertIn(".oom-orb-core", css)
        self.assertIn('data-state="speaking"', css)
        self.assertIn("@keyframes oom-orb-spin", css)
        self.assertIn("@keyframes oom-orb-breathe", css)
        self.assertIn(".oom-status[data-state=\"checking\"]", css)
        self.assertIn("@keyframes oom-status-pulse", css)
        self.assertIn(".oom-safety-notes", css)
        self.assertIn(".oom-system-workbench", css)
        self.assertIn(".oom-system-workbench > summary", css)
        self.assertIn(".oom-workbench-next-action", css)
        self.assertIn(".oom-workbench-counts", css)
        self.assertIn(".oom-work-section", css)
        self.assertIn(".oom-work-badge", css)
        self.assertIn(".oom-work-actions", css)

        presence_start = template.index('class="oom-presence-panel"')
        presence_end = template.index("</section>", presence_start)
        presence_markup = template[presence_start:presence_end]
        form_start = template.index('id="oom_form"')
        form_end = template.index("</form>", form_start)
        form_markup = template[form_start:form_end]
        self.assertIn('id="oom_voice_button"', presence_markup)
        self.assertIn('id="oom_voice_ask_button"', presence_markup)
        self.assertNotIn('id="oom_voice_button"', form_markup)
        self.assertNotIn('id="oom_voice_ask_button"', form_markup)
        self.assertIn(".oom-recent-row", css)
        self.assertIn(".oom-review-metrics", css)
        self.assertIn(".oom-problem-list", css)
        self.assertIn(".oom-voice-readiness", css)
        self.assertIn(".oom-voice-session", css)
        self.assertIn(".oom-voice-events", css)
        self.assertIn(".oom-tool-catalog", css)
        self.assertIn(".oom-tool-row", css)
        self.assertIn(".oom-tool-meta", css)
        self.assertIn(".oom-policy-panel", css)
        self.assertIn(".oom-policy-grid", css)
        self.assertIn(".oom-policy-blocked", css)
        self.assertIn(".oom-review-advisor", css)
        self.assertIn(".oom-advisor-panel", css)
        self.assertIn(".oom-advisor-queue", css)
        self.assertIn(".oom-deploy-instructions", css)
        self.assertIn(".oom-voice-check-ready", css)
        self.assertIn(".oom-voice-check-blocked", css)
        self.assertIn(".oom-voice-status", css)
        self.assertIn(".oom-voice-loop-counter", css)
        self.assertIn(".oom-voice-hint", css)
        self.assertIn(".oom-voice-status-row", css)
        self.assertIn(".oom-cancel-voice-send", css)
        self.assertIn(".oom-answer-controls", css)
        self.assertIn(".oom-speech-control", css)
        self.assertIn(".oom-speech-toggle", css)
        self.assertIn(".oom-quick-drawer", css)
        self.assertIn(".oom-quick-drawer > summary", css)
        self.assertIn(".oom-quick-drawer[open] > summary::after", css)
        self.assertIn(".oom-quick-checks", css)
        self.assertIn(".oom-quick-group", css)
        self.assertIn(".oom-quick-group-label", css)
        self.assertIn("grid-template-columns: repeat(3, minmax(0, 1fr))", css)
        self.assertIn(".oom-trace-filters", css)
        self.assertIn(".oom-trace-search", css)
        self.assertIn(".oom-feedback-controls", css)
        self.assertIn(".oom-feedback-status", css)
        self.assertIn(".oom-recent-details", css)
        self.assertIn(".oom-recent-answer", css)
        self.assertIn(".oom-recent-warning-list", css)
        self.assertIn(".oom-recent-safety-list", css)
        self.assertIn(".oom-recent-link-list", css)
        self.assertIn("font-size: 32px", css)

    def test_litter_detail_uses_existing_litter_api_route(self):
        js = Path("static/js/litterDetail.js").read_text(encoding="utf-8")
        template = Path("templates/litter-detail.html").read_text(encoding="utf-8")

        self.assertIn("/api/pig-weights/litter/${encodeURIComponent(litterId)}", js)
        self.assertNotIn("/api/pig-weights/litter/${encodeURIComponent(litterId)}/detail", js)
        self.assertIn('id="litter_attention_panel"', template)
        self.assertIn("litter-detail-shell", template)
        self.assertIn("litter-detail-page", template)
        self.assertIn('id="litter_detail_back_link"', template)
        self.assertIn('href="/" class="secondary-link">&larr; Back to Dashboard</a>', template)
        self.assertIn("litter-workspace", template)
        self.assertIn("litter-summary-grid", template)
        self.assertIn("litter-side-column", template)
        self.assertIn("litter-piglet-table-wrap", template)
        self.assertIn('id="litter_estimated_wean_date_value"', template)
        self.assertIn('id="litter_wean_attention_start_value"', template)
        self.assertIn('id="mark_weaned_form"', template)
        self.assertIn('id="mark_weaned_button"', template)
        self.assertIn('id="newborn_health_form"', template)
        self.assertIn('id="newborn_health_antiparasitic"', template)
        self.assertIn('id="newborn_health_deworming"', template)
        self.assertIn('id="newborn_health_preview_button"', template)
        self.assertIn('id="newborn_health_apply_button"', template)
        self.assertIn('id="litter_piglet_death_panel"', template)
        self.assertIn('id="piglet_death_form"', template)
        self.assertIn('id="piglet_death_preview_button"', template)
        self.assertIn('id="piglet_death_apply_button"', template)
        self.assertIn('id="litter_sex_count_panel"', template)
        self.assertIn('id="sex_count_form"', template)
        self.assertIn('id="sex_count_preview_button"', template)
        self.assertIn('id="sex_count_apply_button"', template)
        self.assertIn('id="litter_outcome_slaughtered"', template)
        self.assertIn("renderLifecycleOutcomes", js)
        self.assertIn("litter.lifecycle_outcomes", js)
        self.assertIn("/api/pig-weights/litter/${encodeURIComponent(litterId)}/mark-weaned", js)
        self.assertIn("/api/pig-weights/litter/${encodeURIComponent(litterId)}/newborn-health", js)
        self.assertIn("/api/pig-weights/litter/${encodeURIComponent(litterId)}/piglet-deaths", js)
        self.assertIn("/api/pig-weights/litter/${encodeURIComponent(litterId)}/sex-counts", js)
        self.assertIn("renderSexCountPanel", js)
        self.assertIn("previewSexCount", js)
        self.assertIn("submitSexCount", js)
        self.assertIn("antiparasitic_product_id", js)
        self.assertIn("deworming_product_id", js)
        self.assertIn('attention.action_type === "record_litter_newborn_health"', js)
        self.assertIn('method: "POST"', js)
        self.assertIn('attention.action_type === "mark_weaned"', js)
        self.assertNotIn('attention.action_type === "review_or_wean"', js)
        self.assertIn("buildPigletTable", js)
        self.assertIn("wirePigletTableRows", js)
        self.assertIn("data-pig-profile", js)
        self.assertIn("pigProfileHref", js)
        self.assertIn("return_to", js)
        self.assertIn("return_label", js)
        self.assertIn("updateBackLinkFromQuery", js)
        self.assertIn("safeInternalReturnPath", js)
        self.assertIn('params.get("return_to")', js)
        self.assertIn("litter.estimated_wean_date", js)
        self.assertIn("litter.wean_tag_attention_start_date", js)
        self.assertIn("litter-piglet-table", Path("static/css/main.css").read_text(encoding="utf-8"))

    def test_pig_dropdowns_pad_numeric_tags_for_display(self):
        paths = [
            Path("static/js/addLitter.js"),
            Path("static/js/addMating.js"),
            Path("static/js/pigList.js"),
            Path("static/js/pigWeights.form.js"),
            Path("static/js/weightReport.js"),
        ]

        for path in paths:
            js = path.read_text(encoding="utf-8")
            with self.subTest(path=str(path)):
                self.assertIn("padStart(3", js)
                self.assertIn("formatTagNumber", js)

    def test_pig_list_uses_numeric_aware_display_order_and_search(self):
        js = Path("static/js/pigList.js").read_text(encoding="utf-8")

        self.assertIn("pigSortKey", js)
        self.assertIn("sortPigsForDisplay", js)
        self.assertIn("sortPigsForDisplay(data.pigs || [])", js)
        self.assertIn("formattedTagNumber", js)
        self.assertIn("formatTagNumber(pig.tag_number || pig.pig_id)", js)
        self.assertIn("card.href = `/pig/${encodeURIComponent(pig.pig_id)}`", js)

    def test_mating_board_uses_section_aware_sorting(self):
        js = Path("static/js/matings.js").read_text(encoding="utf-8")

        self.assertIn("action_priority", js)
        self.assertIn("actualFarrowing || expectedFarrowing", js)
        self.assertIn(".sort(compareMatingRecords)", js)
        self.assertIn('a.action_section === "needs_action"', js)
        self.assertIn('a.action_section === "closed"', js)
        self.assertIn('compareByActionDate(a, b, "desc")', js)
        self.assertIn("isEligibleForAddLitter", js)
        self.assertIn('/master/add-litter?mating_id=', js)
        self.assertIn("withReturnContext", js)
        self.assertIn('"Back to Breeding Board"', js)
        self.assertIn("return_to", js)

    def test_add_litter_can_prefill_from_mating_query_param(self):
        js = Path("static/js/addLitter.js").read_text(encoding="utf-8")

        self.assertIn("prefillMatingFromUrl", js)
        self.assertIn("new URLSearchParams(window.location.search)", js)
        self.assertIn('params.get("mating_id")', js)
        self.assertIn("handleMatingSelect({ target: select })", js)

    def test_pig_detail_has_controlled_lifecycle_death_action(self):
        template = Path("templates/pig-detail.html").read_text(encoding="utf-8")
        js = Path("static/js/pigDetail.js").read_text(encoding="utf-8")

        self.assertIn('id="lifecycle_action_panel"', template)
        self.assertIn('id="lifecycle_death_form"', template)
        self.assertIn('id="pig_detail_back_link"', template)
        self.assertIn('id="detail_exit_reason"', template)
        self.assertIn('id="detail_carcass_weight"', template)
        self.assertIn("Record Death / Removal", template)
        self.assertIn("/api/pig-weights/pig/${encodeURIComponent(currentPigId)}/lifecycle/death", js)
        self.assertIn('method: "POST"', js)
        self.assertIn("safeInternalReturnPath", js)
        self.assertIn("updateBackLink", js)
        self.assertIn("withPigReturnContext", js)
        self.assertIn("return_label: \"Back to Pig Profile\"", js)
        self.assertIn('params.get("return_to")', js)
        self.assertIn("pig.status === \"Active\" && pig.on_farm === \"Yes\"", js)
        self.assertIn("renderLifecycleHistory", js)
        self.assertIn("pig.lifecycle", js)
        self.assertIn("window.confirm", js)

    def test_pig_child_pages_return_to_pig_profile(self):
        template_expectations = {
            "templates/pig-weight-history.html": 'id="history_back_link"',
            "templates/pig-treatment.html": 'id="treatment_back_link"',
            "templates/pig-treatment-history.html": 'id="treatment_history_back_link"',
            "templates/pig-movement.html": 'id="movement_back_link"',
            "templates/pig-movement-history.html": 'id="movement_history_back_link"',
            "templates/family-tree.html": 'id="family_tree_back_link"',
            "templates/pig-weights.html": 'id="weight_form_back_link"',
        }
        for path, expected in template_expectations.items():
            with self.subTest(path=path):
                self.assertIn(expected, Path(path).read_text(encoding="utf-8"))

        for path in [
            "static/js/pigWeightHistory.js",
            "static/js/pigTreatment.form.js",
            "static/js/pigTreatmentHistory.js",
            "static/js/pigMovement.form.js",
            "static/js/pigMovementHistory.js",
            "static/js/familyTree.js",
        ]:
            js = Path(path).read_text(encoding="utf-8")
            with self.subTest(path=path):
                self.assertIn("pigProfileHref", js)
                self.assertIn("updatePigProfileBackLink", js)
                self.assertIn("Back to Pig Profile", js)

        weight_js = Path("static/js/pigWeights.form.js").read_text(encoding="utf-8")
        self.assertIn("weightFormBackLink", weight_js)
        self.assertIn("safeInternalReturnPath", weight_js)
        self.assertIn("updateBackLinkFromQuery", weight_js)

    def test_breeding_analytics_page_is_read_only_kpi_overview(self):
        template = Path("templates/breeding-analytics.html").read_text(encoding="utf-8")
        js = Path("static/js/breedingAnalytics.js").read_text(encoding="utf-8")
        matings_template = Path("templates/matings.html").read_text(encoding="utf-8")

        self.assertIn("Breeding Analytics", template)
        self.assertIn("Sow Performance", template)
        self.assertIn("Boar Performance", template)
        self.assertIn("/api/pig-weights/breeding-analytics", js)
        self.assertIn("breedingDetailHref", js)
        self.assertIn('return_to: "/breeding-analytics"', js)
        self.assertIn('return_label: "Back to Analytics"', js)
        self.assertNotIn('method: "POST"', js)
        self.assertIn("/breeding-analytics", matings_template)

    def test_breeding_analytics_detail_page_is_read_only_drill_in(self):
        template = Path("templates/breeding-analytics-detail.html").read_text(encoding="utf-8")
        js = Path("static/js/breedingAnalyticsDetail.js").read_text(encoding="utf-8")

        self.assertIn("Breeding Analytics Detail", template)
        self.assertIn('id="breeding_detail_back_link"', template)
        self.assertIn('id="breeding_quality_list"', template)
        self.assertIn('id="breeding_detail_matings_body"', template)
        self.assertIn('id="breeding_detail_litters_body"', template)
        self.assertIn("breedingAnalyticsDetail.js", template)
        self.assertIn("/api/pig-weights/breeding-analytics/${encodeURIComponent(pigId)}", js)
        self.assertIn("renderQuality", js)
        self.assertIn("renderMatings", js)
        self.assertIn("renderLitters", js)
        self.assertIn("updateBackLinkFromQuery", js)
        self.assertIn("safeInternalReturnPath", js)
        self.assertIn("litterDetailHref", js)
        self.assertIn('"Back to Breeding Detail"', js)
        self.assertNotIn('method: "POST"', js)

    def test_weight_form_shows_current_pen_helper_without_changing_payload(self):
        template = Path("templates/pig-weights.html").read_text(encoding="utf-8")
        js = Path("static/js/pigWeights.form.js").read_text(encoding="utf-8")

        self.assertIn('id="current_pen_helper"', template)
        self.assertIn("updateCurrentPenHelper", js)
        self.assertIn("Current pen:", js)
        self.assertIn('moved_to_pen_id: movedToPenSelect.value || ""', js)

    def test_weight_report_has_read_only_refinement_sections(self):
        template = Path("templates/weight-report.html").read_text(encoding="utf-8")
        js = Path("static/js/weightReport.js").read_text(encoding="utf-8")

        self.assertIn("Loss Flags", template)
        self.assertIn('id="loss_flags_body"', template)
        self.assertNotIn("<th>Notes</th>", template)
        self.assertIn("duplicate-marker", js)
        self.assertIn("duplicate_same_day", js)
        self.assertIn("setDateColumnVisibility", js)

    def test_weight_form_confirms_before_saving_duplicate_weight(self):
        js = Path("static/js/pigWeights.form.js").read_text(encoding="utf-8")

        self.assertIn("response.status === 409", js)
        self.assertIn("data.duplicate_weight", js)
        self.assertIn("window.confirm", js)
        self.assertIn("allow_duplicate: true", js)

    def test_weight_form_has_top_save_action_and_blocks_weight_wheel(self):
        template = Path("templates/pig-weights.html").read_text(encoding="utf-8")
        css = Path("static/css/main.css").read_text(encoding="utf-8")
        js = Path("static/js/pigWeights.form.js").read_text(encoding="utf-8")

        self.assertIn('class="form-actions form-actions-primary"', template)
        self.assertIn('id="submit_button"', template)
        self.assertIn('id="submit_button_bottom"', template)
        self.assertIn('class="no-spinner"', template)
        self.assertIn("input.no-spinner::-webkit-inner-spin-button", css)
        self.assertIn('weightKgInput.addEventListener("wheel"', js)
        self.assertIn("event.preventDefault()", js)
        self.assertIn("submitButtons.forEach", js)

    def test_dashboard_labels_monthly_sales_as_exits_not_income(self):
        js = Path("static/js/dashboard.js").read_text(encoding="utf-8")
        template = Path("templates/dashboard.html").read_text(encoding="utf-8")

        self.assertIn("Monthly Sales", template)
        self.assertIn("Livestock Sales", template)
        self.assertIn("Slaughter Sales", template)
        self.assertNotIn('"Sales This Month"', js)
        self.assertIn("livestock_sales_this_month", js)
        self.assertIn("slaughter_sales_this_month", js)
        self.assertIn("meat_sales_this_month", js)
        self.assertIn("slaughter_sales_value_this_month", js)

    def test_dashboard_uses_wide_operational_template_and_existing_read_apis(self):
        template = Path("templates/dashboard.html").read_text(encoding="utf-8")
        js = Path("static/js/dashboard.js").read_text(encoding="utf-8")
        css = Path("static/css/main.css").read_text(encoding="utf-8")

        self.assertIn('class="ops-shell"', template)
        self.assertIn('class="ops-dashboard"', template)
        self.assertIn("Farm Operating Dashboard", template)
        self.assertIn("width: min(100%, 1640px)", css)
        self.assertIn("/api/telemetry/weather/current", js)
        self.assertIn("/api/telemetry/weather/today?date=", js)
        self.assertIn("/api/telemetry/weather/forecast?days=3", js)
        self.assertIn("/api/telemetry/power/current", js)
        self.assertIn("/api/telemetry/irrigation/status?date=", js)
        self.assertIn("/api/telemetry/rollups/daily?date=", js)
        self.assertIn("/api/pig-weights/dashboard", js)
        self.assertIn("/api/reports/daily-summary?date=", js)
        self.assertNotIn('method: "POST"', js)

    def test_dashboard_herd_breakdown_includes_all_counted_categories(self):
        template = Path("templates/dashboard.html").read_text(encoding="utf-8")
        js = Path("static/js/dashboard.js").read_text(encoding="utf-8")

        for field in [
            "sows",
            "boars",
            "gilts",
            "piglets",
            "weaners",
            "growers",
            "finishers",
        ]:
            self.assertIn(f'id="herd_{field}"', template)
            self.assertIn(f'summary.{field}', js)

        for field in ["sold", "slaughtered", "dead", "removed"]:
            self.assertIn(f'id="outcome_{field}"', template)
            self.assertIn(f"lifecycle_{field}_this_month", js)
        self.assertIn("ops-outcome-strip", template)

    def test_slaughter_sale_form_uses_supabase_sales_transaction_endpoints(self):
        template = Path("templates/slaughter-sale.html").read_text(encoding="utf-8")
        js = Path("static/js/slaughterSale.js").read_text(encoding="utf-8")
        dashboard = Path("templates/dashboard.html").read_text(encoding="utf-8")

        self.assertIn("Record Slaughter Sale", template)
        self.assertIn("slaughter-page-shell", template)
        self.assertIn("slaughter-workspace", template)
        self.assertIn("slaughter-entry-column", template)
        self.assertIn("slaughter-ledger-column", template)
        self.assertIn('id="slaughter_sale_form"', template)
        self.assertIn('id="submit_slaughter_sale_top"', template)
        self.assertIn('id="slaughter_pig_rows"', template)
        self.assertIn('id="add_slaughter_pig_button"', template)
        self.assertIn('id="slaughter_batch_total"', template)
        self.assertIn('id="slaughter_search"', template)
        self.assertIn('id="slaughter_status_filter"', template)
        self.assertIn('id="slaughter_payment_filter"', template)
        self.assertIn('id="slaughter_update_panel"', template)
        self.assertIn('id="slaughter_update_form"', template)
        self.assertIn('id="update_line_total"', template)
        self.assertIn('id="update_payment_status"', template)
        self.assertIn('id="update_payment_date"', template)
        self.assertIn('id="update_carcass_weight"', template)
        self.assertIn('value="JC Slaghuis"', template)
        self.assertIn('value="Bartelsfontein"', template)
        self.assertIn('value="Unpaid"', template)
        self.assertIn('value="Confirmed"', template)
        self.assertIn("formatTagNumber", js)
        self.assertIn("padStart(3", js)
        self.assertIn("addPigRow", js)
        self.assertIn("duplicateSelectedPigIds", js)
        self.assertIn("slaughter-line-total", js)
        self.assertIn('fetch("/api/pig-weights/pigs")', js)
        self.assertIn('fetch("/api/sales-transactions"', js)
        self.assertIn('method: "POST"', js)
        self.assertIn('"/api/sales-transactions?sale_stream=Slaughter&limit=25"', js)
        self.assertIn("/cancel", js)
        self.assertIn("data-update-sale-id", js)
        self.assertIn("data-item-count", js)
        self.assertIn("openUpdatePanel", js)
        self.assertIn("submitUpdatePayment", js)
        self.assertIn("/payment", js)
        self.assertIn("payment_date", js)
        self.assertIn("Payment date is required when payment status is Paid.", js)
        self.assertNotIn("Final batch amount for", js)
        self.assertIn('method: "PATCH"', js)
        self.assertIn("applyTransactionFilters", js)
        self.assertIn("table-subtext", js)
        self.assertIn('colspan="6"', js)
        self.assertIn("data-sale-row", js)
        self.assertIn("slaughterSaleDetailHref", js)
        self.assertIn('return_to: "/sales/slaughter"', js)
        self.assertIn('return_label: "Back to Slaughter Sales"', js)
        self.assertIn('item.sale_status === "Completed"', js)
        self.assertIn('item.payment_status === "Paid"', js)
        self.assertIn("table-action-button", js)
        self.assertIn("setSubmitting", js)
        self.assertIn("submitButtons.forEach", js)
        self.assertNotIn("/api/pig-weights/weights", js)
        self.assertNotIn("/api/master/pigs", js)
        self.assertIn("/sales/slaughter", dashboard)

    def test_slaughter_sale_detail_page_reads_one_sale(self):
        template = Path("templates/slaughter-sale-detail.html").read_text(encoding="utf-8")
        js = Path("static/js/slaughterSaleDetail.js").read_text(encoding="utf-8")

        self.assertIn("sale_detail_back", template)
        self.assertIn("sale_detail_summary", template)
        self.assertIn("sale_items_body", template)
        self.assertIn("sale_exit_confirm_form", template)
        self.assertIn("Confirm Pig Exits", template)
        self.assertIn("window.SLAUGHTER_SALE_ID", template)
        self.assertIn("/api/sales-transactions/${encodeURIComponent(saleId)}", js)
        self.assertIn("/api/sales-transactions/${encodeURIComponent(saleId)}/confirm-pig-exits", js)
        self.assertIn('method: "POST"', js)
        self.assertIn('["Completed", "Cancelled"].includes(saleStatus)', js)
        self.assertIn('paymentStatus === "Paid"', js)
        self.assertIn("window.confirm", js)
        self.assertIn("updateBackButtonFromQuery", js)
        self.assertIn("safeInternalReturnPath", js)
        self.assertIn("saleDetailFallbackPath", js)
        self.assertIn('params.get("return_to")', js)
        self.assertIn("/sales/slaughter", js)
        self.assertIn("/sales-dashboard", js)
        self.assertIn("renderItems", js)

    def test_sales_dashboard_is_transaction_overview_with_filters_and_drill_in(self):
        template = Path("templates/sales-dashboard.html").read_text(encoding="utf-8")
        js = Path("static/js/salesDashboard.js").read_text(encoding="utf-8")

        self.assertIn("Sales Overview", template)
        self.assertIn('id="sales_period_filter"', template)
        self.assertIn('id="sales_month_filter"', template)
        self.assertIn('id="sales_year_filter"', template)
        self.assertIn('id="sales_stream_filter"', template)
        self.assertIn('id="sales_transactions_body"', template)
        self.assertIn('id="sales_total_value"', template)
        self.assertIn("/api/sales-transactions?limit=100", js)
        self.assertIn("/api/pig-weights/sales-dashboard", js)
        self.assertIn("filteredTransactions", js)
        self.assertIn("renderSalesTotals", js)
        self.assertIn("data-sale-row", js)
        self.assertIn("saleDetailHref", js)
        self.assertIn('return_to: "/sales-dashboard"', js)
        self.assertIn('return_label: "Back to Sales Dashboard"', js)
        self.assertIn("selected_month", js)
        self.assertIn("selected_year", js)

    def test_pig_allocation_page_is_read_only_business_readiness_view(self):
        app_source = Path("app.py").read_text(encoding="utf-8")
        routes = Path("modules/pig_weights/pig_weights_routes.py").read_text(encoding="utf-8")
        service = Path("modules/pig_weights/pig_weights_service.py").read_text(encoding="utf-8")
        template = Path("templates/pig-allocation.html").read_text(encoding="utf-8")
        js = Path("static/js/pigAllocation.js").read_text(encoding="utf-8")
        dashboard = Path("templates/dashboard.html").read_text(encoding="utf-8")
        css = Path("static/css/main.css").read_text(encoding="utf-8")

        self.assertIn('@app.route("/pig-allocation")', app_source)
        self.assertIn('render_template("pig-allocation.html")', app_source)
        self.assertIn('@pig_weights_bp.route("/pig-allocation-readiness", methods=["GET"])', routes)
        self.assertIn("get_pig_allocation_readiness", service)
        self.assertIn("writes_to_sheets", service)
        self.assertIn("writes_to_supabase", service)
        self.assertIn("DEFAULT_ALLOCATION_SETTINGS", service)
        self.assertIn("business_rules", service)
        self.assertIn("Pig Allocation Readiness", template)
        self.assertIn('id="allocation_body"', template)
        self.assertIn('id="allocation_rules"', template)
        self.assertIn('id="bucket_filter"', template)
        self.assertIn("/api/pig-weights/pig-allocation-readiness", js)
        self.assertIn("BUCKET_ORDER", js)
        self.assertIn("renderRules", js)
        self.assertIn("business_rules", js)
        self.assertIn("Needs Classification", js)
        self.assertIn("formatAdg", js)
        self.assertIn("growth_basis", js)
        self.assertIn("post_wean_daily_gain_kg", js)
        self.assertIn("estimated_meat_ready_date", js)
        self.assertIn("estimated_abattoir_ready_date", js)
        self.assertIn("outlet_priority", js)
        self.assertIn("recommended_action", js)
        self.assertIn("marketing_readiness", js)
        self.assertIn("suggested_purpose", js)
        self.assertIn("suggested_purpose_reason", js)
        self.assertIn("suggested_purpose_confidence", js)
        self.assertIn("litter_quality", js)
        self.assertIn("average_daily_gain_kg", js)
        self.assertIn("No writes are made from this page", js)
        self.assertIn("<th>Recommended Action</th>", template)
        self.assertIn("<th>Suggested Purpose</th>", template)
        self.assertIn("<th>Growth</th>", template)
        self.assertIn("<th>Timing</th>", template)
        self.assertIn("<th>Weaning</th>", template)
        self.assertNotIn('method: "POST"', js)
        self.assertIn('href="/pig-allocation"', dashboard)
        self.assertIn('href="/meat-planning"', dashboard)
        self.assertIn(".allocation-filters", css)
        self.assertIn(".allocation-rules", css)

    def test_meat_planning_page_is_read_only_pipeline_view(self):
        app_source = Path("app.py").read_text(encoding="utf-8")
        routes = Path("modules/pig_weights/pig_weights_routes.py").read_text(encoding="utf-8")
        controller = Path("modules/pig_weights/pig_weights_controller.py").read_text(encoding="utf-8")
        service = Path("modules/pig_weights/pig_weights_service.py").read_text(encoding="utf-8")
        template = Path("templates/meat-planning.html").read_text(encoding="utf-8")
        js = Path("static/js/meatPlanning.js").read_text(encoding="utf-8")
        dashboard = Path("templates/dashboard.html").read_text(encoding="utf-8")
        allocation_template = Path("templates/pig-allocation.html").read_text(encoding="utf-8")
        css = Path("static/css/main.css").read_text(encoding="utf-8")

        self.assertIn('@app.route("/meat-planning")', app_source)
        self.assertIn('render_template("meat-planning.html")', app_source)
        self.assertIn('@pig_weights_bp.route("/meat-planning", methods=["GET"])', routes)
        self.assertIn("get_meat_planning_data", controller)
        self.assertIn("get_meat_planning_summary", service)
        self.assertIn("get_pig_allocation_readiness", service)
        self.assertIn("writes_to_sheets", service)
        self.assertIn("writes_to_supabase", service)
        self.assertIn("Meat Planning", template)
        self.assertIn('id="meat_planning_body"', template)
        self.assertIn('id="meat_planning_summary"', template)
        self.assertIn('id="meat_planning_rules"', template)
        self.assertIn('id="demand_now_input"', template)
        self.assertIn('id="demand_30_input"', template)
        self.assertIn("Temporary calculation only. Nothing is saved.", template)
        self.assertIn("/api/pig-weights/meat-planning", js)
        self.assertIn("ready_now", js)
        self.assertIn("fallback_abattoir", js)
        self.assertIn("minimum_preorder_needed_30_days", js)
        self.assertIn("renderDemandScenario", js)
        self.assertIn("demandResultText", js)
        self.assertIn("No writes are made from this page", js)
        self.assertNotIn('method: "POST"', js)
        self.assertNotIn("localStorage", js)
        self.assertIn('href="/meat-planning"', dashboard)
        self.assertIn('href="/meat-planning"', allocation_template)
        self.assertIn(".meat-planning-filters", css)
        self.assertIn(".meat-demand-grid", css)

    def test_print_sheets_page_is_read_only_weight_capture_sheet(self):
        template = Path("templates/print-sheets.html").read_text(encoding="utf-8")
        js = Path("static/js/printSheets.js").read_text(encoding="utf-8")

        self.assertIn("Weekly Weight Capture Sheet", template)
        self.assertIn("Previous Weight Date", template)
        self.assertIn("Previous Weight", template)
        self.assertIn("New Weight", template)
        self.assertIn("Current Pen", template)
        self.assertIn("New Pen", template)
        self.assertIn("Notes", template)
        self.assertNotIn("Pig_ID", template)
        self.assertIn('fetch("/api/pig-weights/pigs")', js)
        self.assertIn('fetch("/api/pig-weights/pens")', js)
        self.assertNotIn("method: \"POST\"", js)
        self.assertIn("window.print", js)
        self.assertIn("multiple", template)
        self.assertIn("/bulk-weights", template)

    def test_bulk_weights_page_uses_batch_preflight_and_local_draft(self):
        template = Path("templates/bulk-weights.html").read_text(encoding="utf-8")
        js = Path("static/js/bulkWeights.js").read_text(encoding="utf-8")

        self.assertIn("Bulk Weight Entry", template)
        self.assertIn("Save Draft", template)
        self.assertIn("Upload Batch", template)
        self.assertIn("Previous Weight Date", template)
        self.assertIn("New Weight", template)
        self.assertIn('fetch("/api/pig-weights/pigs")', js)
        self.assertIn('fetch("/api/pig-weights/pens")', js)
        self.assertIn("/api/pig-weights/weights-batch/preflight", js)
        self.assertIn("/api/pig-weights/weights-batch", js)
        self.assertIn("window.localStorage", js)
        self.assertIn("Blank rows will be skipped", js)
        self.assertIn("clearUploadedAndDuplicateDraftRows", js)
        self.assertIn("already has a weight entry", js)
        self.assertIn("Blocked/existing rows skipped", js)


if __name__ == "__main__":
    unittest.main()
