LogLevel warn
MaxLogSize 1048576
Listen /run/cups/cups.sock
Browsing Off
WebInterface No
DefaultAuthType Basic
PreserveJobHistory Yes
PreserveJobFiles No
RequestRoot /tmp/cups
TempDir /tmp/cups
DataDir /usr/share/cups
ServerRoot /run/cups
StateDir /run/cups
<Location />
  Order deny,allow
  Deny all
  Allow localhost
</Location>
