LogLevel warn
MaxLogSize 1048576
Listen localhost:631
Browsing Off
WebInterface No
DefaultAuthType Basic
PreserveJobHistory Yes
PreserveJobFiles No
RequestRoot /tmp/cups
TempDir /tmp/cups
DataDir /usr/share/cups
ServerRoot /etc/cups
StateDir /run/cups
<Location />
  Order deny,allow
  Deny all
  Allow localhost
</Location>
