"""Deterministic non-doctrine projections for static agent asset cards."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path


AGENT_CARD_SOURCES = {
    "beacon": "docs/09-vault-brain/02-agents/marketing/BEACON.md",
    "butcher": "docs/09-vault-brain/02-agents/sales/BUTCHER.md",
    "gatekeeper": "docs/09-vault-brain/02-agents/farm/GATEKEEPER.md",
    "herdmaster": "docs/09-vault-brain/02-agents/farm/HERDMASTER.md",
    "ledger": "docs/09-vault-brain/02-agents/sales/LEDGER.md",
    "oom-sakkie": "docs/09-vault-brain/02-agents/farm/OOM_SAKKIE.md",
    "quartermaster": "docs/09-vault-brain/02-agents/farm/QUARTERMASTER.md",
    "rootline": "docs/09-vault-brain/02-agents/farm/ROOTLINE.md",
    "sam": "docs/09-vault-brain/02-agents/sales/SAM.md",
}

GENERATED_MARKER = "<!-- GENERATED BY scripts/build_agent_card_projections.py; DO NOT EDIT -->"


def _digest(path: Path) -> str:
    # Git may materialize CRLF on Windows and LF in CI. Projection identity is
    # the normalized tracked text, not platform-specific checkout bytes.
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _role(text: str, source: str) -> str:
    match = re.search(r"^Role:\s*(.+?)\s*$", text, flags=re.MULTILINE)
    if not match:
        raise ValueError(f"canonical agent source lacks Role line: {source}")
    return match.group(1)


def render_agent_card(repo_root: Path, agent_id: str) -> str:
    source_relative = AGENT_CARD_SOURCES[agent_id]
    source = repo_root / source_relative
    asset_relative = f"static/assets/agents/{agent_id}/agent.json"
    asset = repo_root / asset_relative
    registry_relative = "static/assets/agents/agent_registry.json"
    registry_path = repo_root / registry_relative
    if not source.is_file() or not asset.is_file() or not registry_path.is_file():
        raise FileNotFoundError(f"projection input missing for {agent_id}")
    metadata = json.loads(asset.read_text(encoding="utf-8"))
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    matches = [item for item in registry.get("agents", []) if item.get("agent_id") == agent_id]
    if len(matches) != 1:
        raise ValueError(f"central asset registry entry mismatch for {agent_id}")
    registered = matches[0]
    if metadata.get("agent_id") != agent_id:
        raise ValueError(f"asset metadata ID mismatch for {agent_id}")
    for field in ("display_name", "role_label"):
        if metadata.get(field) != registered.get(field):
            raise ValueError(f"asset metadata {field} differs from central registry for {agent_id}")
    source_text = source.read_text(encoding="utf-8")
    voice_name = metadata.get("voice_name") or "Not selected"
    voice_approved = bool(metadata.get("voice_approved_for_production"))
    lines = [
        GENERATED_MARKER,
        f"# {metadata['display_name']} Runtime Asset Projection",
        "",
        "Status: `GENERATED / NON_DOCTRINE`",
        "",
        f"- Agent ID: `{agent_id}`",
        f"- UI role label: `{metadata['role_label']}`",
        f"- Canonical role: {_role(source_text, source_relative)}",
        f"- Canonical doctrine: `{source_relative}`",
        f"- Canonical doctrine SHA-256: `{_digest(source)}`",
        f"- Asset metadata: `{asset_relative}`",
        f"- Asset metadata SHA-256: `{_digest(asset)}`",
        f"- Central asset registry: `{registry_relative}`",
        f"- Central asset registry SHA-256: `{_digest(registry_path)}`",
        f"- Voice asset: `{voice_name}`; production approved: `{str(voice_approved).lower()}`",
        "",
        "This card grants no authority and records no operational status. Read the",
        "canonical Vault source and mandatory mission pack before using this agent.",
        "Regenerate with `python scripts/build_agent_card_projections.py`.",
        "",
    ]
    return "\n".join(lines)


def projection_findings(repo_root: Path) -> tuple[list[str], list[str]]:
    findings: list[str] = []
    checked: list[str] = []
    card_root = repo_root / "static/assets/agents"
    actual_ids = {path.parent.name for path in card_root.glob("*/agent.md")}
    expected_ids = set(AGENT_CARD_SOURCES)
    if actual_ids != expected_ids:
        findings.append(
            "agent-card projection set mismatch: "
            f"expected={sorted(expected_ids)} actual={sorted(actual_ids)}"
        )
    for agent_id, source_relative in sorted(AGENT_CARD_SOURCES.items()):
        card_relative = f"static/assets/agents/{agent_id}/agent.md"
        checked.extend([
            source_relative,
            f"static/assets/agents/{agent_id}/agent.json",
            "static/assets/agents/agent_registry.json",
            card_relative,
        ])
        try:
            expected = render_agent_card(repo_root, agent_id)
            actual = (repo_root / card_relative).read_text(encoding="utf-8")
        except (OSError, UnicodeError, ValueError, KeyError, json.JSONDecodeError) as exc:
            findings.append(f"agent-card projection unavailable for {agent_id}: {exc}")
            continue
        if actual != expected:
            findings.append(f"agent-card projection drift: {card_relative}")
    return findings, checked


def write_agent_cards(repo_root: Path) -> None:
    for agent_id in sorted(AGENT_CARD_SOURCES):
        target = repo_root / f"static/assets/agents/{agent_id}/agent.md"
        target.write_text(render_agent_card(repo_root, agent_id), encoding="utf-8", newline="\n")
